name: Quarto Publish
on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: '3.10'
          activate-environment: r-reticulate
          channels: conda-forge,defaults

      - name: Install Python dependencies via Conda
        run: |
          conda install -n r-reticulate -c conda-forge numpy pandas matplotlib scipy statsmodels seaborn polars requests beautifulsoup4 session-info -y
          # add any other Python packages your analysis uses here
        shell: bash -l {0}

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R Packages
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          install.packages(c("reticulate", "knitr", "rmarkdown", "tidyverse", "mdsr", "lubridate", "Lahman", "babynames", "rvest", "NHANES", "patchwork", "mosaicData"))
          # add any other R packages your analysis uses here
        shell: Rscript {0}

      - name: Prepare README as Index
        run: cp README.md index.md

      - name: Render Quarto
        run: |
          export RETICULATE_PYTHON=$(conda info --base)/envs/r-reticulate/bin/python
          quarto render
        shell: bash -l {0}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
      - name: Compute lowercase image name
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}:latest" >> "$GITHUB_ENV"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        continue-on-error: true
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/nomisteco0532/my-r-env:latest
